/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InProgressRouteImport } from './routes/in-progress'
import { Route as IndexRouteImport } from './routes/index'

const InProgressRoute = InProgressRouteImport.update({
  id: '/in-progress',
  path: '/in-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/in-progress': typeof InProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/in-progress': typeof InProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/in-progress': typeof InProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/in-progress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/in-progress'
  id: '__root__' | '/' | '/in-progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InProgressRoute: typeof InProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/in-progress': {
      id: '/in-progress'
      path: '/in-progress'
      fullPath: '/in-progress'
      preLoaderRoute: typeof InProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InProgressRoute: InProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
